# Compiler/config
CXX := g++
CXXFLAGS := -Wall -Werror -Wpedantic
CPPFLAGS := -Iinclude -MMD -MP
DEBUGFLAGS := -ggdb -fsanitize=address -fsanitize=undefined

ifdef DEBUG
	CXXFLAGS += $(DEBUGFLAGS)
else
	CXXFLAGS += -O2
endif

# Dirs
SRCDIR := src
INCDIR := include
OBJDIR := obj
BINDIR := bin

# Binary
GAME := $(BINDIR)/twinStickShooter

# Source files
GAME_SOURCES := \
	$(SRCDIR)/main.cpp \
	$(SRCDIR)/entity.cpp \
	$(SRCDIR)/enemy.cpp \
	$(SRCDIR)/player.cpp \
	$(SRCDIR)/mapstate.cpp

# Object files (mirror directory structure under obj/)
GAME_OBJECTS := $(GAME_SOURCES:%.cpp=$(OBJDIR)/%.o)

# Dependency files (auto-generated by -MMD -MP)
DEPS := $(GAME_OBJECTS:.o=.d)

.PHONY: all clean run fresh test

all: $(GAME)

$(GAME): $(GAME_OBJECTS) | $(BINDIR)
	$(CXX) $(CXXFLAGS) $^ -o $@

# Compile (ensure obj subdirs exist)
$(OBJDIR)/src/%.o: $(SRCDIR)/%.cpp
	@mkdir -p $(@D)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

# Create bin/
$(BINDIR):
	mkdir -p $@

run: $(GAME)
	./$(GAME)

clean:
	rm -rf $(OBJDIR) $(BINDIR)

test: $(GAME)
	echo "No tests yet"

fresh: clean all

# Include auto-generated header dependencies
-include $(DEPS)
